name: Sleeper

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Sleep five hours
        run: |
          sleep 18000
          echo done
